import { assetUrl } from './lib/assets.js';
const galleryImages = [
  '01.webp',
  '02.webp',
  '03.webp',
  '04.webp',
  '05.webp',
  '06.webp',
  '07.webp',
  '08.webp',
  '09.webp',
  '10.jpg',
  '11.jpg',
  '12.jpg',
  '13.jpg',
  '14.jpg',
  '15.jpg',
  '16.jpg',
  '17.jpg',
  '18.jpg',
  '19.jpg',
  '20.jpg',
];
export const content = {
  pageMode: 'hero-landing',
  site: {
    title: 'DEBT TECH 2026',
    date: '13 ноября 2026',
    city: 'Москва',
    logo: assetUrl('assets/debttech-logo.svg'),
  },
  menu: {
    groups: [],
    cta: {
      label: 'Ранняя регистрация',
      href: '#tariffs',
    },
    secondaryCta: {
      label: 'Забронировать стенд',
      href: 'https://t.me/anna_joys',
      modal: 'stand-booking',
    },
    sidebar: {
      contactLabel: 'Контакты для связи',
      contactEmail: 'redchief@rvzrus.ru',
      organizersLabel: 'ОРГАНИЗАТОРЫ',
      organizersImage: assetUrl('assets/icons/organizers.svg'),
    },
  },
  hero: {
    title: 'DEBT TECH 2026',
    backgroundImage: assetUrl('assets/hero-debttech-2026.png'),
    backgroundImageAdaptive: assetUrl('assets/hero-debttech-2026-adaptive.png'),
    bottomTitle:
      'Стратегии, технологии и инновационные сервисы для работы с долговыми обязательствами',
    countdownLabel: 'Время до запуска',
    countdownTarget: '2026-11-13T00:00:00+03:00',
    countdown: [
      { value: '00', label: 'дней' },
      { value: '00', label: 'часов' },
      { value: '00', label: 'минут' },
      { value: '00', label: 'секунд' },
    ],
  },
  ticker: {
    items: [
      '800+ делегатов',
      '70+ спикеров',
      '50+ участников выставки',
      '3 сцены',
      'Креативная вечерняя программа',
      'Интерактивные зоны',
      'Пресс-студия',
      'Фуршет',
      'VIP-резиденции',
      'Afterparty',
    ],
  },
  heroVideo: {
    title: 'Как это было в 2025',
    previewUrl:
      'https://kinescope.io/embed/dd7dQ3BMbTCeSfteZFXCiS?autopause=false&autoplay=true&background=true&controls=false&loop=true&muted=true&transparent=false',
    embedUrl:
      'https://kinescope.io/embed/dd7dQ3BMbTCeSfteZFXCiS?autopause=false&autoplay=true&background=false&controls=true&loop=true&muted=true&transparent=true',
    widgetUrl:
      'https://kinescope.io/embed/dd7dQ3BMbTCeSfteZFXCiS?autopause=false&autoplay=true&background=false&controls=true&loop=true&muted=false&transparent=false',
  },
  venue: {
    title: 'Место проведения',
    date: '13 ноября 2026',
    name: 'TAU — пространство музыкальных культур',
    address: 'Москва, Рязанский проспект, 8Ас10',
    routeLabel: 'Смотреть на карте',
    routeHref:
      'https://yandex.ru/maps/?text=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C%20%D0%A0%D1%8F%D0%B7%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BF%D1%80%D0%BE%D1%81%D0%BF%D0%B5%D0%BA%D1%82%2C%208%D0%90%D1%8110',
    images: [
      { image: assetUrl('assets/images/venue/event.webp'), alt: 'Событие в пространстве TAU' },
      { image: assetUrl('assets/images/venue/lounge.webp'), alt: 'Лаунж-зона TAU' },
      { image: assetUrl('assets/images/venue/hall.webp'), alt: 'Главный зал TAU' },
    ],
  },
  gallery: {
    title: 'Кадры с DEBT TECH 2025',
    ctaLabel: 'Смотреть все фото',
    href: 'https://rvz.bitrix24.ru/~0IZ9x',
    items: galleryImages.map((name, index) => ({
      image: assetUrl(`assets/images/gallery/${name}`),
      alt: `DEBT TECH 2025 — кадр ${index + 1}`,
    })),
  },
  organizer: {
    title: 'Организатор\nфорума',
    contacts: {
      label: 'Контакты для связи:',
      phone: '+7 965 786 88 46',
      phoneHref: 'tel:+79657868846',
      email: 'redchief@rvzrus.ru',
      websiteLabel: 'Сайт',
      websiteHref: 'https://rvzrus.ru/',
      channels: [
        { id: 'telegram', label: 'Телеграм', href: 'https://t.me/rvzrus_chat' },
        { id: 'max', label: 'Макс', href: 'https://max.ru/id9725047250_biz' },
        { id: 'whatsapp', label: 'Ватсап', href: 'https://wa.me/79657868846' },
      ],
    },
    media: {
      title: 'СМИ «РЫНОК ВЗЫСКАНИЯ»',
      license: 'Эл № ФС77-82673 от 10.02.2022',
      logo: assetUrl('assets/images/organizer/rvz-logo.svg'),
      href: 'https://rvzrus.ru/',
    },
    photo: {
      image: assetUrl('assets/images/organizer/pko-300-2025.png'),
      alt: 'Участники рейтинга ПКО-300 2025 с наградами',
    },
    rating: {
      title: 'Рейтинг ПКО-300',
      description: 'Уникальный инструмент оценки коллекторских компаний',
      href: 'https://pko300.ru/',
    },
    metrics: {
      title: 'Единственное медиа о профессиональном взыскании',
      items: [
        { value: '50 000+', label: 'постоянных читателей' },
        { value: '1000+', label: 'участников конференций в 2025 году' },
      ],
    },
    features: [
      'Совместные исследования\nс лидерами отрасли',
      'Актуальные новости рынка',
      'Обзоры it-технологий в коллекшн',
      'Судебная практика',
      'Интервью с ключевыми персонами',
    ],
    navigator: {
      title: 'DEBT TECH Навигатор',
      logo: assetUrl('assets/images/organizer/navigator-logo.svg'),
      image: assetUrl('assets/images/organizer/navigator-preview.png'),
      description:
        'Навигатор по технологическим решениям для работы с долговыми обязательствами: от аналитики до продажи, взыскания и банкротства.',
      href: 'https://navigator.debt-tech.ru/',
    },
  },
  otherConferences: {
    title: 'Другие конференции\nСМИ «Рынок Взыскания»',
    range: '[ 2021 – 2026 ]',
    items: [
      {
        title: 'DOLG TALK Казань',
        year: '2026',
        href: 'https://kazan.dolgtalk.ru/',
        image: assetUrl('assets/images/other-conferences/dolg-talk-kazan-2026.png'),
      },
      {
        title: 'DOLG TALK',
        year: '2026',
        href: 'https://dolgtalk.ru/',
        image: assetUrl('assets/images/other-conferences/dolg-talk-2026.png'),
      },
      {
        title: 'DOLG TALK Сибирь',
        year: '2026',
        href: 'https://novosib.dolgtalk.ru/',
        image: assetUrl('assets/images/other-conferences/dolg-talk-siberia-2026.jpg'),
      },
      {
        title: 'DEBT TECH',
        year: '2025',
        href: 'https://2025.debt-tech.ru/',
        image: assetUrl('assets/images/other-conferences/debt-tech-2025.jpg'),
      },
      {
        title: 'DOLG TALK',
        year: '2025',
        href: 'https://dolgtalk.ru/2025',
        image: assetUrl('assets/images/other-conferences/dolg-talk-2025.png'),
      },
      {
        title: 'DOLG TALK Казань',
        year: '2025',
        href: 'https://kazan.dolgtalk.ru/2025',
        image: assetUrl('assets/images/other-conferences/dolg-talk-kazan-2025.png'),
      },
      {
        title: 'DEBT TECH',
        year: '2024',
        href: 'https://debttech.rvzrus.ru/',
        image: assetUrl('assets/images/other-conferences/debt-tech-2024.png'),
      },
      {
        title: 'Аналитика и финансы долговых портфелей 2.0',
        titleLines: ['Аналитика и финансы', 'долговых портфелей 2.0'],
        year: '2023',
        href: 'https://rvzrus.ru/news/2521',
        image: assetUrl('assets/images/other-conferences/analytics-finance-2023.png'),
      },
      {
        title: 'Аналитика и финансы долговых портфелей',
        titleLines: ['Аналитика и финансы', 'долговых портфелей'],
        year: '2022',
        href: 'https://rvzrus.ru/news/2464',
        image: assetUrl('assets/images/other-conferences/analytics-finance-2022.png'),
      },
      {
        title: 'Петербургский форум взыскателей',
        titleLines: ['Петербургский форум', 'взыскателей'],
        year: '2021',
        href: 'https://rvzrus.ru/news/2083',
        image: assetUrl('assets/images/other-conferences/petersburg-collectors-2021.png'),
      },
    ],
  },
  tariffs: {
    eyebrow: 'Multipass',
    title: 'Welcome',
    logoImage: assetUrl('assets/images/tariffs/logo-form.svg'),
    handImage: assetUrl('assets/images/tariffs/hand-spaceman.png'),
    offer:
      'Скидка 50% на один билет любого тарифа для представителя компании, которая впервые участвует в DEBT TECH.',
    agreement: 'Скидка предоставляется по согласованию с организаторами.',
    note: 'Стоимость актуальна до 1 октября включительно',
    ctaLabel: 'Принять участие',
    ctaModal: 'early-registration',
    items: [
      {
        id: 'business',
        title: 'Деловой',
        price: '44 000 ₽',
        background: assetUrl('assets/images/tariffs/business-bg.svg'),
        icon: assetUrl('assets/images/tariffs/business-icon.svg'),
        features: [
          { label: 'Деловая программа', active: true },
          { label: 'Кофе-брейк, обед', active: true },
          { label: 'Фотоотчет', active: true },
          { label: 'Презентации спикеров', active: true },
          { label: 'Видеозапись конференции', active: true },
          { label: 'Креативная вечерняя программа', active: false },
          { label: 'Space Disco Afterparty', active: false },
        ],
      },
      {
        id: 'full',
        title: 'Полный',
        price: '49 000 ₽',
        background: assetUrl('assets/images/tariffs/full-bg.svg'),
        icon: assetUrl('assets/images/tariffs/full-icon.svg'),
        features: [
          { label: 'Деловая программа', active: true },
          { label: 'Кофе-брейк, обед', active: true },
          { label: 'Фотоотчет', active: true },
          { label: 'Презентации спикеров', active: true },
          { label: 'Видеозапись конференции', active: true },
          { label: 'Креативная вечерняя программа', active: true },
          { label: 'Space Disco Afterparty', active: false },
        ],
      },
      {
        id: 'full-plus',
        title: 'Полный Plus',
        price: '66 000 ₽',
        background: assetUrl('assets/images/tariffs/full-plus-bg.svg'),
        icon: assetUrl('assets/images/tariffs/full-plus-icon.svg'),
        features: [
          { label: 'Деловая программа', active: true },
          { label: 'Кофе-брейк, обед', active: true },
          { label: 'Фотоотчет', active: true },
          { label: 'Презентации спикеров', active: true },
          { label: 'Видеозапись конференции', active: true },
          { label: 'Креативная вечерняя программа', active: true },
          { label: 'Space Disco Afterparty', active: true },
        ],
      },
    ],
  },
  aboutForum: {
    eyebrow: 'О форуме',
    title: 'DEBT TECH 2026',
    description: 'Ежегодная форум-выставка о технологиях на рынке долговых активов',
    titleLines: ['Ежегодная', 'форум-выставка', 'о технологиях', 'на рынке долговых', 'активов'],
    planetImage: assetUrl('assets/images/about-forum/planet-v3.png'),
    shuttleImage: assetUrl('assets/images/about-forum/shuttle-v3.png'),
    logoImage: assetUrl('assets/debttech-logo.svg'),
    meetingLines: ['До встречи', '13 ноября в Москве'],
    features: [
      'Эксклюзивная деловая программа с практическими кейсами',
      'Активное участие представителей государственных органов и СРО',
      'Спецформаты и услуги для участников',
      'Доступ к готовым решениям: демостенды, контакты интеграторов и разработчиков',
      'Новые партнёры и сделки',
    ],
    stats: [
      { value: '800+', label: 'участников' },
      { value: '400+', label: 'компаний' },
      { value: '100+', label: 'спикеров' },
      { value: '50+', label: 'партнеров' },
    ],
    tags: [
      {
        id: 'artificial-intelligence',
        label: 'Искусственный интеллект',
        icon: assetUrl('assets/images/about-forum/tags/artificial-intelligence.svg'),
      },
      {
        id: 'big-data',
        label: 'Big Data',
        icon: assetUrl('assets/images/about-forum/tags/big-data.svg'),
      },
      {
        id: 'ai-agents',
        label: 'AI-агенты',
        icon: assetUrl('assets/images/about-forum/tags/ai-agents.svg'),
      },
      {
        id: 'speech-analytics',
        label: 'Речевая аналитика',
        icon: assetUrl('assets/images/about-forum/tags/speech-analytics.svg'),
      },
      { id: 'bi', label: 'BI', icon: assetUrl('assets/images/about-forum/tags/bi.svg') },
      {
        id: 'low-code',
        label: 'Low-code',
        icon: assetUrl('assets/images/about-forum/tags/low-code.svg'),
      },
      {
        id: 'import-substitution',
        label: 'Импортозамещение',
        icon: assetUrl('assets/images/about-forum/tags/import-substitution.svg'),
      },
      {
        id: 'data-driven',
        label: 'Data driven',
        icon: assetUrl('assets/images/about-forum/tags/data-driven.svg'),
      },
      {
        id: 'e-justice',
        label: 'Электронное правосудие',
        icon: assetUrl('assets/images/about-forum/tags/e-justice.svg'),
      },
      {
        id: 'distressed-debt',
        label: 'Проблемный долг',
        icon: assetUrl('assets/images/about-forum/tags/distressed-debt.svg'),
      },
      {
        id: 'cession',
        label: 'Цессия',
        icon: assetUrl('assets/images/about-forum/tags/cession.svg'),
      },
      {
        id: 'investments',
        label: 'Инвестиции',
        icon: assetUrl('assets/images/about-forum/tags/investments.svg'),
      },
      {
        id: 'e-auctions',
        label: 'Электронные торги',
        icon: assetUrl('assets/images/about-forum/tags/e-auctions.svg'),
      },
    ],
  },
  contacts: {
    title: 'Контактная информация',
    accreditationEmail: 'org@rvzrus.ru',
    tickets: {
      title: 'Приобрести билет участника:',
      email: 'a.fefilova@rvzrus.ru',
      phone: '+7 965 786 88 46',
      phoneHref: 'tel:+79657868846',
    },
    partnership: {
      title: 'По вопросам партнерства и выступления:',
      email: 'org@rvzrus.ru',
      phone: '+7 925 223 67 07',
      phoneHref: 'tel:+79252236707',
    },
    website: 'https://rvzrus.ru/',
  },
  footer: {
    copyright: '© 2026 DEBT TECH. Все права защищены.',
    privacyLabel: 'Политика конфиденциальности и персональных данных',
    privacyHref: 'https://rvzrus.ru/politic',
  },
  forms: {
    eventId: 'debt-tech-2026',
    contactEmail: 'redchief@rvzrus.ru',
    telegramUrl: 'https://t.me/anna_joys',
    channels: [
      { id: 'telegram', label: 'Telegram', href: 'https://t.me/rvzrus_chat' },
      { id: 'max', label: 'Max', href: 'https://max.ru/id9725047250_biz' },
    ],
  },
};
